### ISSUE TITLE
LED PeriodicRunnable

### ISSUE THREAD

**Issue by cfinn68916** [Brown-County-FIRST-Robotics/1716-2024-robot#17]
A class to control the LED strips. SHOULD NOT BE A Subsystem, rather it should extend PeriodicRunnable. Needs to be accessed everywhere in the code, so have global instance with getInstance static method?

How it will be used:
- Tell the driver when intake eats ring
- Make it do something cool before the match and during autonomus

Bare minimum:
- Can set entire strip color
- Logs the color of each LED

More features:
- Flashing lights to signal different events (ie:ready to shoot)

**Comment by gldeA** [comment]
https://github.com/Brown-County-FIRST-Robotics/1716-2024-robot/blob/CF_PeriodicRunnable_Docs/docs/PeriodicRunnable.md#periodicrunnable-class
