### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by cfinn68916** [Brown-County-FIRST-Robotics/1716-2024-robot#2]
We should find a place to export our javadocs to. Maybe github pages?

**Comment by gldeA** [comment]
Good Idea:

- [ ] Assign someone
- [ ] figure out how we can do this
- [ ] do this
- [ ] document this

**Comment by gldeA** [comment]
In the action it should:
- Run the JavaDoc task (`run: ./gradlew javadoc` in Github Actions)
- Push that output (in `build/docs/javadoc`) to Github Pages somehow (read Github Pages docs)

https://pages.github.com/
https://github.com/features/actions
https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/robot-code-ci.html
https://github.wpilib.org/allwpilib/docs/release/java/index.html

**Comment by gldeA** [comment]
🎉
