### ISSUE TITLE
Accepting and Storing Note (Feeder)

### ISSUE THREAD

**Issue by LucasLubinski** [Brown-County-FIRST-Robotics/1716-2024-robot#22]
The pizza box shooter needs to be able to accept the note from the intake or/and a person and load / hold the note until we are ready to shoot. 

- Need to find the proper PRM to hand note into the holding arm behind the shooter.
- Determine what position the motor will be in when loaded and waiting for note.

**Comment by gldeA** [comment]
- [ ] Change to use Smart Motion
- [ ] Make it use ThriftyBot encoder

**Comment by gldeA** [comment]
Change to use light sensor rather than encoder

**Comment by gldeA** [comment]
The feeder is now a wheel, we need to change the code to match that. How exactly should we run it?
