### ISSUE TITLE
Driver rate limiting

### ISSUE THREAD

**Issue by cfinn68916** [Brown-County-FIRST-Robotics/1716-2024-robot#36]
Add in rate limiting in TeleopDrive. Use frc.utils.DualRateLimiter. Have two limiters, one for angular velocity and one for translational velocity. For the linear velocity, it should limit the norm of the joystick, not the x and y components individually.

**Comment by gldeA** [comment]
- [ ] Account for friction in the acceleration using vector math (see image)
- [ ] Limit acceleration, but not deceleration or rotational, speed to make driving feel smoother and more responsive
![20240315_175223](https://github.com/Brown-County-FIRST-Robotics/1716-2024-robot/assets/92763974/7285c35e-4644-4091-a299-c73037aa1e46)
